# Generated by Django 4.1.13 on 2024-02-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_goal', models.FloatField(blank=True, null=True)),
                ('benchpress_goal', models.FloatField(blank=True, null=True)),
                ('squat_goal', models.FloatField(blank=True, null=True)),
                ('deadlift_goal', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DjangoFitApp.user')),
            ],
        ),
    ]
