# Generated by Django 4.1.13 on 2024-02-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFitApp', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
