# Generated by Django 4.1.13 on 2024-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFitApp', '0003_rename_user_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='benchpress_goal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deadlift_goal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='squat_goal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_goal',
            field=models.FloatField(default=0.0),
        ),
    ]
