# Generated by Django 4.1.13 on 2024-02-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFitApp', '0004_alter_userprofile_benchpress_goal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
    ]
