# Generated by Django 4.1.13 on 2024-03-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFitApp', '0009_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='./DjangoFitApp/FullStackAppDefaultProfilePicture.jpg', upload_to='profile_pictures/'),
        ),
    ]
