# Generated by Django 4.1.13 on 2024-03-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFitApp', '0012_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='djangoFitApp/profile_pictures/DefaultProfilePicture.jpg', upload_to='djangoFitApp/profile_pictures/'),
        ),
    ]
