# Generated by Django 4.1.13 on 2024-03-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFitApp', '0017_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='benchpress_current',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='benchpress_goal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='benchpress_progress',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deadlift_current',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deadlift_goal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deadlift_progress',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='squat_current',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='squat_goal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='squat_progress',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_current',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_goal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_progress',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
