# Generated by Django 4.1.13 on 2024-03-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFitApp', '0021_alter_userprofile_benchpress_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='/media/profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
